[package]
name = "grex_native"
version = "0.1.0"
authors = []
edition = "2021"

[lib]
name = "grex_native"
path = "src/lib.rs"
crate-type = ["cdylib"]

[dependencies]
grex = { version = "1.4.4", default-features = false }
rustler = { version = "0.30.0", features = ["nif_version_2_16"] }
